require("dotenv").config();
const mongoose = require("mongoose");
const User = require("./models/User");

const studentNames = [
    "Aarav K",
    "Aarthi R",
    "Abinaya S",
    "Abishek M",
    "Adithya P",
    "Aishwarya V",
    "Akash R",
    "Akila K",
    "Akshaya M",
    "Alamelu S",
    "Amarnath P",
    "Amudha R",
    "Anbarasi K",
    "Anbu M",
    "Anitha S",
    "Anjali R",
    "Annamalai K",
    "Aravind M",
    "Arjun P",
    "Arul S",
    "Aruna K",
    "Ashwin R",
    "Aswini M",
    "Azhagu P",
    "Balaji S",
    "Balamurugan R",
    "Banu K",
    "Bharath M",
    "Bhavani P",
    "Bhavya S",
    "Chandran R",
    "Chitra K",
    "Dhanalakshmi M",
    "Dhanush P",
    "Dharani S",
    "Dharshini R",
    "Dinesh K",
    "Divya M",
    "Durga P",
    "Elango S",
    "Elavarasi R",
    "Eshwar K",
    "Fathima M",
    "Gajalakshmi P",
    "Ganesh S",
    "Gayathri R",
    "Gokul K",
    "Gopinath M",
    "Gowri P",
    "Harini S",
    "Harish R",
    "Haritha K",
    "Hemalatha M",
    "Hema P",
    "Ilango S",
    "Ilavarasan R",
    "Indhu K",
    "Indumathi M",
    "Ishwar P",
    "Jagan S",
    "Jagadeesh R",
    "Janani K",
    "Jayanthi M",
    "Jayaprakash P",
    "Jeeva S",
    "Jegan R",
    "Jothika K",
    "Kabilan M",
    "Kalaiarasi P",
    "Kalaiselvi S",
    "Kalyani R",
    "Kamatchi K",
    "Kannan M",
    "Karthik P",
    "Karthika S",
    "Karthikeyan R",
    "Kavitha K",
    "Kavya M",
    "Keerthana P",
    "Keerthi S",
    "Keerthivasan R",
    "Kiran K",
    "Krishnan M",
    "Kumaran P",
    "Lakshmi S",
    "Lakshmipriya R",
    "Latha K",
    "Lavanya M",
    "Logesh P",
    "Lokesh S",
    "Madhan R",
    "Madhavi K",
    "Madhumitha M",
    "Mahalakshmi P",
    "Mahesh S",
    "Malathi R",
    "Malarvizhi K",
    "Manikandan M",
    "Manivannan P",
    "Meena S",
    "Meenakshi R",
    "Meenalochani K",
    "Mohan M",
    "Mohanasundaram P",
    "Mukesh S",
    "Muthukumar R",
    "Nandhini K",
    "Nandhakumar M",
    "Natarajan P",
    "Natarani S",
    "Naveen R",
    "Nila K",
    "Nirmala M",
    "Nithish P",
    "Nivetha S",
    "Pavithra R",
    "Palanisamy K",
    "Parvathi M",
    "Poornima P",
    "Prabhu S",
    "Prabhakaran R",
    "Pradeep K",
    "Prakash M",
    "Pranav P",
    "Praveen S",
    "Priya R",
    "Priyadharshini K",
    "Priyanka M",
    "Rahul P",
    "Raja S",
    "Rajalakshmi R",
    "Rajan K",
    "Rajesh M",
    "Rajeshkumar P",
    "Rakesh S",
    "Ranjani R",
    "Ranjith K",
    "Ranjithkumar M",
    "Revathi P",
    "Rithika S",
    "Rohit R",
    "Rukmani K",
    "Sakthi M",
    "Sakthivel P",
    "Sandhya S",
    "Sanjay R",
    "Santhosh K",
    "Saranya M",
    "Saravanan P",
    "Saroja S",
    "Sathish R",
    "Sathya K",
    "Sathyaraj M",
    "Selvakumar P",
    "Selvi S",
    "Senthil R",
    "Senthilkumar K",
    "Shalini M",
    "Sharmila P",
    "Shobana S",
    "Shruthi R",
    "Sivakumar K",
    "Siva M",
    "Sridevi P",
    "Sriram S",
    "Sudha R",
    "Suresh K",
    "Sureshkumar M",
    "Surya P",
    "Sushmitha S",
    "Swetha R",
    "Tamilselvi K",
    "Tharun M",
    "Tharunika P",
    "Thilagavathi S",
    "Thiru R",
    "Thirumagal K",
    "Udhaya M",
    "Udhayakumar P",
    "Uma S",
    "Usha R",
    "Vani K",
    "Varun M",
    "Vasanthi P",
    "Vasanth S",
    "Vasanthakumar R",
    "Vasanthika K",
    "Vasanthraj M",
    "Vetrivel P",
    "Vidya S",
    "Vignesh R",
    "Vigneshwar K",
    "Vijay M",
    "Vijayalakshmi P",
    "Vijaykumar S",
    "Vinay R",
    "Vinitha K",
    "Vinod M",
    "Vishwa P",
    "Yamuna S",
    "Yogesh R",
    "Yuvan K",
    "Abhirami M",
    "Ajith P",
    "Akshara S",
    "Amala R",
    "Anusuya K",
    "Bhuvanesh M",
    "Charan P",
    "Deivanai S",
    "Devika R",
    "Gautham K",
    "Hema Priya M",
    "Ilakkiya P",
    "Janarthanan S",
    "Jayashree R",
    "Kavin K",
    "Keerthika M",
    "Lokeshwari P",
    "Mahendran S",
    "Muthu R",
    "Nandha K",
    "Pavani M",
    "Prithvi P",
    "Raghu S",
    "Rajkumar R",
    "Sakthipriya K",
    "Santhiya M",
    "Shankar P",
    "Sridevi S",
    "Thamarai R",
    "Umesh K",
    "Valli M",
    "Varsha P",
    "Venkatesh S",
    "Vidyasagar R",
    "Vimal K",
    "Vinayak M",
    "Vishnu P",
    "Yuvaraj S"
];

const seed = async () => {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        console.log("Connected to MongoDB...");

        let createdCount = 0;
        let skippedCount = 0;

        const studentsPerClass = 30;
        const sections = ['A', 'B', 'C'];
        const studentsPerSection = 10;

        for (let classIndex = 0; classIndex < 8; classIndex++) {
            const className = (classIndex + 1).toString(); // 1 to 8
            const startIndex = classIndex * studentsPerClass;
            const endIndex = startIndex + studentsPerClass;

            for (let i = startIndex; i < endIndex; i++) {
                const fullName = studentNames[i];
                if (!fullName) break; // In case less names

                const username = fullName.toLowerCase().replace(/\s+/g, ".");

                const exists = await User.findOne({ username });
                if (!exists) {
                    const sectionIndex = Math.floor((i - startIndex) / studentsPerSection);
                    const section = sections[sectionIndex];
                    const studentIndexInSection = (i - startIndex) % studentsPerSection;
                    const registerNumber = `${className}${section}${String(101 + studentIndexInSection).padStart(3, '0')}`;

                    await new User({
                        username,
                        password: username + "123",
                        role: "student",
                        studentName: fullName,
                        className,
                        section,
                        registerNumber
                    }).save();
                    console.log(`✓ Added: ${fullName} (${username}) - Class ${className}${section} - ${registerNumber}`);
                    createdCount++;
                } else {
                    console.log(`– Skipped (Already exists): ${fullName} (${username})`);
                    skippedCount++;
                }
            }
        }

        console.log(`\nResults:\nCreated: ${createdCount}\nSkipped: ${skippedCount}`);
        process.exit(0);
    } catch (err) {
        console.error("Error seeding students:", err);
        process.exit(1);
    }
};

seed();